[package]
name = "hello_blockchain"
version = "0.0.0"

[addresses]
std = "0x1"
hello_blockchain = "_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'